### ISSUE TITLE
Related popups for new items aren't working right

### ISSUE THREAD

**Issue by kmorey** [geex-arts/django-jet#126]
An example can be found on the demo site:

http://demo.jet.geex-arts.com/admin/menu/menuitemcategory/2/#/tab/inline_1/
1. Click add another menu item
2. Click the plus icon on the new row
3. The popup doesn't open in the iframe related popup tab, it opens in full window.

**Comment by f1nality** [comment]
@kmorey thanks for report! fixed in dev and will be released in 1.0.2

**Comment by kmorey** [comment]
It's still not working with what appears to be 1.0.2 on your demo page.

If you open the related popup from the existing "new row" that is there on page load it works fine. If you add any additional rows however, those related popups do not work correctly.

**Comment by f1nality** [comment]
Yes, it was fixed for stacked inline, but not tabular. I'll update the fix.

**Comment by SalahAdDin** [comment]
Please :D

**Comment by f1nality** [comment]
Fixed in 1.0.3
